VCF_FIELDS = ['CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER',
              'INFO', 'FORMAT', 'ANCESTRYDNA_DATA']

HEADER_V1 = [
    "#Below is a text version of your DNA file from Ancestry.com DNA, LLC.  THIS",
    "#INFORMATION IS FOR YOUR PERSONAL USE AND IS INTENDED FOR GENEALOGICAL RESEARCH",
    "#ONLY.  IT IS NOT INTENDED FOR MEDICAL OR HEALTH PURPOSES.  THE EXPORTED DATA IS",
    "#SUBJECT TO THE AncestryDNA TERMS AND CONDITIONS, BUT PLEASE BE AWARE THAT THE",
    "#DOWNLOADED DATA WILL NO LONGER BE PROTECTED BY OUR SECURITY MEASURES."
    "#",
    "#Genetic data is provided below as five TAB delimited columns.  Each line",
    "#corresponds to a SNP.  Column one provides the SNP identifier (rsID where",
    "#possible).  Columns two and three contain the chromosome and basepair position",
    "#of the SNP using human reference build 37.1 coordinates.  Columns four and five",
    "#contain the two alleles observed at this SNP (genotype).  The genotype is reported",
    "#on the forward (+) strand with respect to the human reference.",
]
HEADER_V2 = [
    "#Below is a text version of your DNA file from Ancestry.com DNA, LLC.  THIS",
    "#INFORMATION IS FOR YOUR PERSONAL USE AND IS INTENDED FOR GENEALOGICAL RESEARCH",
    "#ONLY.  IT IS NOT INTENDED FOR MEDICAL OR HEALTH PURPOSES.  THE EXPORTED DATA IS",
    "#SUBJECT TO THE AncestryDNA TERMS AND CONDITIONS, BUT PLEASE BE AWARE THAT THE",
    "#DOWNLOADED DATA WILL NO LONGER BE PROTECTED BY OUR SECURITY MEASURES.",
    "#WHEN YOU DOWNLOAD YOUR RAW DNA DATA, YOU ASSUME ALL RISK OF STORING,",
    "#SECURING AND PROTECTING YOUR DATA.  FOR MORE INFORMATION, SEE ANCESTRYDNA FAQS.",
    "#",
    "#Genetic data is provided below as five TAB delimited columns.  Each line",
    "#corresponds to a SNP.  Column one provides the SNP identifier (rsID where",
    "#possible).  Columns two and three contain the chromosome and basepair position",
    "#of the SNP using human reference build 37.1 coordinates.  Columns four and five",
    "#contain the two alleles observed at this SNP (genotype).  The genotype is reported",
    "#on the forward (+) strand with respect to the human reference.",
]
HEADER_V3 = [
    "#Below is a text version of your DNA file from Ancestry.com DNA, LLC.  THIS",
    "#INFORMATION IS FOR YOUR PERSONAL USE AND IS INTENDED FOR GENEALOGICAL RESEARCH",
    "#ONLY.  IT IS NOT INTENDED FOR MEDICAL, DIAGNOSTIC, OR HEALTH PURPOSES.  THE EXPORTED DATA IS",
    "#SUBJECT TO THE AncestryDNA TERMS AND CONDITIONS, BUT PLEASE BE AWARE THAT THE",
    "#DOWNLOADED DATA WILL NO LONGER BE PROTECTED BY OUR SECURITY MEASURES.",
    "#WHEN YOU DOWNLOAD YOUR RAW DNA DATA, YOU ASSUME ALL RISK OF STORING,",
    "#SECURING AND PROTECTING YOUR DATA.  FOR MORE INFORMATION, SEE ANCESTRYDNA FAQS.",
    "#",
    "#Genetic data is provided below as five TAB delimited columns.  Each line",
    "#corresponds to a SNP.  Column one provides the SNP identifier (rsID where",
    "#possible).  Columns two and three contain the chromosome and basepair position",
    "#of the SNP using human reference build 37.1 coordinates.  Columns four and five",
    "#contain the two alleles observed at this SNP (genotype).  The genotype is reported",
    "#on the forward (+) strand with respect to the human reference.",
]


CHROM_ORDER = {
    'chr1': '1',
    'chr2': '2',
    'chr3': '3',
    'chr4': '4',
    'chr5': '5',
    'chr6': '6',
    'chr7': '7',
    'chr8': '8',
    'chr9': '9',
    'chr10': '10',
    'chr11': '11',
    'chr12': '12',
    'chr13': '13',
    'chr14': '14',
    'chr15': '15',
    'chr16': '16',
    'chr17': '17',
    'chr18': '18',
    'chr19': '19',
    'chr20': '20',
    'chr21': '21',
    'chr22': '22',
    'chrX': '23',
    'chrY': '24',
    'chrM': '25',
    'chrMT': '25',
    'Chr1': '1',
    'Chr2': '2',
    'Chr3': '3',
    'Chr4': '4',
    'Chr5': '5',
    'Chr6': '6',
    'Chr7': '7',
    'Chr8': '8',
    'Chr9': '9',
    'Chr10': '10',
    'Chr11': '11',
    'Chr12': '12',
    'Chr13': '13',
    'Chr14': '14',
    'Chr15': '15',
    'Chr16': '16',
    'Chr17': '17',
    'Chr18': '18',
    'Chr19': '19',
    'Chr20': '20',
    'Chr21': '21',
    'Chr22': '22',
    'ChrX': '23',
    'ChrY': '24',
    'ChrM': '25',
    'ChrMT': '25',
    '1': '1',
    '2': '2',
    '3': '3',
    '4': '4',
    '5': '5',
    '6': '6',
    '7': '7',
    '8': '8',
    '9': '9',
    '10': '10',
    '11': '11',
    '12': '12',
    '13': '13',
    '14': '14',
    '15': '15',
    '16': '16',
    '17': '17',
    '18': '18',
    '19': '19',
    '20': '20',
    '21': '21',
    '22': '22',
    'X': '23',
    'Y': '24',
    'M': '25',
    'MT': '25',
}

CHROM_MAP = {
    '1': '1',
    '2': '2',
    '3': '3',
    '4': '4',
    '5': '5',
    '6': '6',
    '7': '7',
    '8': '8',
    '9': '9',
    '10': '10',
    '11': '11',
    '12': '12',
    '13': '13',
    '14': '14',
    '15': '15',
    '16': '16',
    '17': '17',
    '18': '18',
    '19': '19',
    '20': '20',
    '21': '21',
    '22': '22',
    '23': 'X',
    '24': 'Y',
    '25': 'X',
}
